### ISSUE TITLE
Sensors and Switches to manage the AUX load

### ISSUE THREAD

**Issue by RoganDawes** [kellerza/sunsynk#109]
Existing sensor definitions can be found [here](https://github.com/kellerza/sunsynk/blob/main/sunsynk/definitions.py)

### You Inverter

I am using a Sunsynk 8kw Hybrid inverter.

### Describe the issue/bug and what you expect

I would like to be able to manage the settings and switches related to the AUX load. You can see them in the Sunsynk app under Inverter ... Settings, AUX Settings.

These would appear to be the registers at registers 234-239, 241, and bit 12 of register 280.

### Logs (if applicable)

```
modbus -s 1 127.0.0.1 234 235 236 237 238 239 280
234: 0 0x0
235: 1 0x1
236: 5100 0x13ec
237: 50 0x32
238: 5400 0x1518
239: 60 0x3c
280: 12288 0x3000
```

**Comment by kellerza** [comment]
Can you try creating your own sensors? You can do this with the MULTI addon and creating your own custom sensor file

https://kellerza.github.io/sunsynk/reference/mysensors

**Comment by kellerza** [comment]
This `mysensors.py` should get you started. You can probably suggest better names, these are directly translated.

```python
from sunsynk.rwsensors import SelectRWSensor, SwitchSensor

SENSORS += SelectRWSensor(234, "Force Gen", switch=("Off", "Force"))
SENSORS += SelectRWSensor(
    235,
    "AUX port",
    options={0: "Disable", 1: "Load Output", 2: "Inverter Input"},
)
SENSORS += SelectRWSensor(280, "Micro Grid export", bitmask=1<<12, options={1<<12: "Grid", 0:"Off"})
```

**Comment by RoganDawes** [comment]
Thanks for this. In the meantime, my need for this control has diminished, as I have simply set the threshold to the minimum, so that it stays on all the time, and control the load with a smart relay.

I'll still test it out, though.

**Comment by RoganDawes** [comment]
So I tried it, and got a few errors. Some of which I could resolve, but I'm not sure about the SelectRWSensor with the `switch` option. That code appears to be commented out in the version that I have running (and in the latest github version).

This is what I ended up with from your initial code:
```python

**Comment by kellerza** [comment]
In the latest version there should be a SwitchRWSensor

**Comment by RoganDawes** [comment]
Aha! I'll check that out. Thanks!

**Comment by cods4** [comment]
I'm trying to achieve the same thing using SwitchRWSensor, but unfortuantely my Python skills aren't as good as RoganDawes'
I am able to set and read the bits, but I get log entries like this:
`WARNING unknown1: Unknown register value 272`

This is my code
`SENSORS += SwitchRWSensor(280, "Unknown1", on=0x01, bitmask=0x000)
SENSORS += SwitchRWSensor(280, "Gen Peak Shaving", on=0x10, bitmask=0x010)
SENSORS += SwitchRWSensor(280, "Grid Peak Shaving", on=0x100, bitmask=0x100)
SENSORS += SwitchRWSensor(280, "Micro Grid Export", on=0x1000, bitmask=0x1000)
SENSORS += SwitchRWSensor(280, "Unknown3", on=0x2000, bitmask=0x2000)
SENSORS += SwitchRWSensor(280, "Unknown4", on=0x4000, bitmask=0x4000)
SENSORS += SwitchRWSensor(280, "DRM", on=0x8000, bitmask=0x8000)`

I think I need some kind of bitwise operator to read back the bits (rather than 'on=0x100', but I haven't been able to make it work with the SwitchRWSensor function.

**Comment by kellerza** [comment]
The `bitmask` likely already do what you want.

When *reading* a register from the Inverter the value is masked (`value & bitmask`) and then compared with on/off. [ref](https://github.com/kellerza/sunsynk/blob/main/sunsynk/sensors.py#L53)

When *writing* a register to the Inverter:
- The current register value is read
- The value from the sensors updates that value with the bitmask (see [patch](https://github.com/kellerza/sunsynk/blob/main/sunsynk/helpers.py#L109))
- The new value is written to the inverter

An 'unknown value' error usually indicates that a selectrwsensor received an undefined option (and likely needs a bitmask to only consider the correct bits)

Use the Python REPL to play around with these concepts/convert

```python
>>> 0b1
1
>>> 0b10
2
>>> 0x1
1
>>> 0x10
16
>>> bin(272)
'0b100010000'
>>> hex(272)
'0x110'
>>> 1<<12
4096
>>> 0xfff & 0x1
1
``

**Comment by RoganDawes** [comment]
No point leaving this open, I think.
